site_name: 开源软件通识：知识体系指南
site_url: https://X-lab2017.github.io/oss101-bok/
repo_name: oss101-bok
repo_url: https://github.com/X-lab2017/oss101-bok
edit_uri: tree/main/docs
# Copyright
copyright: Copyright &copy; 2024 X-lab<br>The website content is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>

# Configuration
theme:
  name: material
  favicon: assets/favicon.jpeg
  custom_dir: docs/overrides
  logo: assets/favicon.jpeg
  language: zh
  icon:
    repo: fontawesome/brands/github #右上角图标
  features:
    - navigation.expand
    - announce.dismiss
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - content.code.copy # 代码支持拷贝
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换至深色模式
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换至浅色模式
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra:
  alternate:
    - name: 简体中文
      link: /oss101-bok/
      lang: zh
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/X-lab2017

    - icon: fontawesome/regular/envelope #联系方式图标
      link: mailto:<wwang@dase.ecnu.edu.cn> #邮件联系方式
  status:
    new: 最近添加
nav:
  - 首页: index.md
  - 教材:
    - 开源软件通识：知识体系指南:
        - 第 1 章 开源知识体系:
          - 1.1 背景与目标: textbook/chapter_1/chapter_1_1.md
          - 1.2 知识体系与框架: textbook/chapter_1/chapter_1_2.md
          - 1.3 本书组织与结构: textbook/chapter_1/chapter_1_3.md
        - 第一部分 基础:
          - 第 2 章 基本概念:
              - 2.1: textbook/chapter_2/chapter_2_1.md
          - 第 3 章 许可证:
              - 3.1 许可证: textbook/chapter_3/chapter_3_1.md
              - 3.2 开源许可证: textbook/chapter_3/chapter_3_2.md
              - 3.3 贡献者许可协议: textbook/chapter_3/chapter_3_3.md
              - 3.4 著作权: textbook/chapter_3/chapter_3_4.md
              - 3.5 作品: textbook/chapter_3/chapter_3_5.md
              - 3.6 衍生作品: textbook/chapter_3/chapter_3_6.md
              - 3.7 专利: textbook/chapter_3/chapter_3_7.md
              - 3.8 自述文件: textbook/chapter_3/chapter_3_8.md
          - 第 4 章 元数据:
              - 4.1: textbook/chapter_4/chapter_4_1.md
        - 第二部分 治理:
          - 第 5 章 企业:
              - 5.1: textbook/chapter_5/chapter_5_1.md
          - 第 6 章 社区:
              - 6.1: textbook/chapter_6/chapter_6_1.md
          - 第 7 章 项目:
              - 7.1: textbook/chapter_7/chapter_7_1.md
          - 第 8 章 开发者:
              - 8.1: textbook/chapter_8/chapter_8_1.md
        - 第三部分 安全:
          - 第 9 章 基础:
              - 9.1: textbook/chapter_9/chapter_9_1.md
          - 第 10 章 应用:
              - 10.1: textbook/chapter_10/chapter_10_1.md
          - 第 11 章 运营:
              - 11.1: textbook/chapter_11/chapter_11_1.md
        - 第四部分 应用:
          - 第 12 章 技术:
              - 12.1: textbook/chapter_12/chapter_12_1.md
          - 第 13 章 方案:
              - 13.1: textbook/chapter_13/chapter_13_1.md
          - 第 14 章 测评:
              - 14.1: textbook/chapter_14/chapter_14_1.md
          - 第 15 章 服务:
              - 15.1: textbook/chapter_15/chapter_15_1.md
  - 标签: tag.md
  - 日志:
      - index: blog/index.md
plugins:
  - glightbox
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - search
  - git-revision-date-localized: # 支持文档创建时间显示， https://github.com/timvink/mkdocs-git-revision-date-localized-plugin
      locale: zh
      enable_creation_date: true
      type: date
      exclude:
        - index.md
        - tag.md
  - git-committers:
      # enabled: !ENV [CI, false]
      repository: X-lab2017/oss101-bok
      branch: master

      exclude:
        - index.md
        - tag.md
  - tags:
      tags_file: tag.md #分类标签
  - blog: #博客配置
      post_date_format: full #时间
      draft: true
      draft_if_future_date: true #自动将具有未来日期的帖子标记为草稿
      post_readtime: true
      post_readtime_words_per_minute: 265 #计算帖子的阅读时间时读者每分钟预计阅读的字数
      post_url_format: "{date}/{slug}"
      pagination_url_format: "page/{page}"
      authors_file: "{blog}/.authors.yml" #作者信息